title: Zachary Salloum
description: Mechanical engineering portfolio featuring CAD and FEA projects
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
