title: Zachary Salloum
description: Mechanical engineering portfolio featuring CAD and FEA projects
theme: jekyll-theme-slate
sass:
  style: compressed
<link rel="stylesheet" href="{{ site.baseurl }}/assets/css/custom.css">
