title: Zachary Salloum
subheader: Linkedin | Resume
description: Mechanical engineering portfolio featuring CAD and FEA projects
theme: jekyll-theme-slate
sass:
  style: compressed

markdown: kramdown
kramdown:
  input: GFM
